- package.json
- packages/server/src/server.ts
Minor changes to fix integration points.
> Integration improvements

- packages/sdk/src/components/Model/ModelCell.tsx
- packages/sdk/src/components/Notebook/Notebook.tsx
- packages/sdk/src/components/Package/Package.tsx
> feat: add links to embed entire notebook/model

- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Notebook/Notebook.tsx
> feat: model code snippet

- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Model/ModelCell.tsx
> feat: Add schedule annotations to notebooks and models UI

- packages/server/src/service/model.spec.ts
- packages/server/src/service/package.spec.ts
- packages/server/src/service/package.ts
ticket https://github.com/pathwaysdata/pathways-service/issues/47
> chore: service/package.ts unit tests

- packages/sdk/src/components/Package/Schedules.tsx
ticket https://github.com/pathwaysdata/pathways-service/issues/111
> feat: hide schedules with no data

- package-lock.json
- package.json
- packages/app/tsconfig.json
- packages/server/src/dto/connection.dto.spec.ts
- packages/server/src/dto/connection.dto.ts
- packages/server/src/dto/index.ts
- packages/server/src/dto/package.dto.spec.ts
- packages/server/src/dto/validate.spec.ts
- packages/server/src/service/model.spec.ts
- packages/server/src/service/model.ts
- packages/server/src/service/package.spec.ts
ticket https://github.com/pathwaysdata/pathways-service/issues/45
> feat: connections manifest validation

- README.md
- api-doc.yaml
- packages/app/src/components/BreadcrumbNav.tsx
- packages/app/src/components/ModelPage.tsx
- packages/app/src/components/PackagePage.tsx
- packages/app/src/components/ProjectPage.tsx
- packages/app/src/main.tsx
- packages/sdk/src/client/api.ts
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Model/ModelCell.tsx
- packages/sdk/src/components/Notebook/Notebook.tsx
- packages/sdk/src/components/Package/Config.tsx
- packages/sdk/src/components/Package/Databases.tsx
- packages/sdk/src/components/Package/Models.tsx
- packages/sdk/src/components/Package/Package.tsx
- packages/sdk/src/components/Package/Schedules.tsx
- packages/sdk/src/components/Project/About.tsx
- packages/sdk/src/components/Project/Packages.tsx
- packages/sdk/src/components/Project/Project.tsx
- packages/sdk/src/components/QueryResult/QueryResult.tsx
- packages/server/src/api.ts
- packages/server/src/server.ts
- packages/server/src/service/model.ts
Add projects to resource hierarchy.
> Publisher projects

- README.md
- api-doc.yaml
- package-lock.json
- packages/sdk/src/client/api.ts
- packages/server/package.json
- packages/server/src/api.ts
- packages/server/src/dto/connection.dto.ts
- packages/server/src/service/model.ts
Add Trino connector to the publisher and Snowflake connection options
Once [PR #2178](https://github.com/malloydata/malloy/pull/2178) is merged, the connector version will be updated here to support passing additional configs to the Trino connector.
> add trino connection & snowflake connection options

- packages/sdk/src/components/Package/Package.tsx
https://github.com/ms2data/service/issues/322
> fix: admin panel spacing

- bun.lock
- packages/server/src/constants.ts
- packages/server/src/service/project.ts
Adds README.md to project create / update
> Catches errors when project directory doesn't exist.

- packages/app/src/components/BreadcrumbNav.tsx
Fills the JS console on every load.
> Fixes react warning about onClick not being on Button

- api-doc.yaml
- packages/sdk/src/client/api.ts
- packages/sdk/src/components/Package/Connections.tsx
- packages/sdk/src/components/Package/Databases.tsx
- packages/sdk/src/components/Package/Package.tsx
- packages/server/src/api.ts
- packages/server/src/service/connection.ts
- packages/server/src/service/project.ts
* New "Connection" panel in package view.
* Updates embedded Database view (with DB size)
* Connection API no longer returns connection details (password/host/username)
> Adds connection panel to publisher, updates Database panel

- api-doc.yaml
- bun.lock
- packages/sdk/package.json
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/styles.ts
- packages/server/src/service/model.ts
* Updates Publisher to return SourceInfos in ApiCompiledModel
* Updates Model.tsx to use ModelExplorer to display models. 
* 
https://github.com/user-attachments/assets/3c74c30b-942c-4f3f-b62d-c483305530c7
> Use Explorer in publisher

- packages/sdk/src/components/Project/ConnectionExplorer.tsx
- packages/server/src/controller/connection.controller.ts
- packages/server/src/server.ts
* Sets tableKey to tableName & sets tablePaht to "schema.tableNmae"
* Minor lint fixes
> Fix publisher schema-explorer front end

- packages/sdk/src/components/Project/ConnectionExplorer.tsx
- packages/server/src/service/db_utils.ts
https://github.com/user-attachments/assets/c02b9790-c71a-435e-8cb0-c5b19930697e
> Support for Postgres in SchemaExplorer

- packages/app/src/components/ModelPage.tsx
- packages/app/src/components/ScratchNotebookPage.tsx
- packages/app/src/main.tsx
- packages/sdk/package.json
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Model/SourcesExplorer.tsx
- packages/sdk/src/components/Model/index.ts
- packages/sdk/src/components/MutableNotebook/EditableMalloyCell.tsx
- packages/sdk/src/components/MutableNotebook/ModelPicker.tsx
- packages/sdk/src/components/MutableNotebook/MutableCell.tsx
- packages/sdk/src/components/MutableNotebook/MutableNotebook.tsx
- packages/sdk/src/components/MutableNotebook/index.ts
- packages/sdk/src/components/NotebookManager.ts
- packages/sdk/src/components/Package/Package.tsx
- packages/sdk/src/components/Package/PublisherPackageProvider.tsx
- packages/sdk/src/components/Package/index.ts
- packages/sdk/src/components/index.ts
UI mostly works.
Things to do:
* Lifecyle- listing & opening & deleting your ScratchNotebooks
* Import existing `.malloynb` notebooks
* Further UI iteration (it's still a bit cludgy)
* Integrate with extension/service to push notebooks to server
https://github.com/user-attachments/assets/ba38e0c9-adcb-482e-bf4e-1d5ef553f509
> Initial version of ScratchNotebook

- api-doc.yaml
- packages/python-client/malloy_publisher_sdk/api/models/get_model.py
- packages/python-client/malloy_publisher_sdk/models/model.py
- packages/python-client/malloy_publisher_sdk/models/notebook.py
- packages/sdk/src/components/ApiErrorDisplay.tsx
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Model/SourcesExplorer.tsx
- packages/sdk/src/components/Notebook/Notebook.tsx
- packages/sdk/src/components/Package/FileTreeView.tsx
- packages/server/src/errors.ts
- packages/server/src/service/model.spec.ts
- packages/server/src/service/model.ts
- packages/server/src/service/package.spec.ts
- packages/server/src/service/package.ts
Server returns more meaningful errors.
ListModels/ListNotebooks return errors status of items.
Model.tsx/Notebook.tsx show  meaningful error message.
https://github.com/user-attachments/assets/4e141aaa-1d10-41a2-8526-8e902ffc5244
> Better UI error messages

- packages/sdk/src/components/Home/Home.tsx
- packages/sdk/src/components/Loading.tsx
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Notebook/Notebook.tsx
- packages/sdk/src/components/Package/Databases.tsx
- packages/sdk/src/components/Package/Models.tsx
- packages/sdk/src/components/Package/Notebooks.tsx
- packages/sdk/src/components/Package/Schedules.tsx
- packages/sdk/src/components/Project/About.tsx
- packages/sdk/src/components/Project/ConnectionExplorer.tsx
- packages/sdk/src/components/Project/Packages.tsx
- packages/sdk/src/components/QueryResult/QueryResult.tsx
- packages/sdk/src/components/RenderedResult/RenderedResult.tsx
- packages/sdk/src/components/RenderedResult/ResultContainer.tsx
- packages/sdk/src/components/index.ts
<Loading> is a uniform animated loading widget.
Also implements "suspense" properly in 
https://github.com/user-attachments/assets/89207a35-aa04-46cb-b89e-d8f3753b19c1
> Uniform, animated Loading spinners

- packages/sdk/src/components/MutableNotebook/MutableCell.tsx
- packages/sdk/src/components/MutableNotebook/MutableNotebook.tsx
* Makes buttons float.
* Removes header bar.
* Markdown is click-to-edit and auto-save when you click out.
https://github.com/user-attachments/assets/ac280e45-3b23-4c27-bce3-097d13a8d6d0
> Update the Worksheet UI (buttons)

- .github/workflows/npm-sdk.yml
Add Version # to NPM deploy action
> improve npm action

- packages/app/src/index.ts
So they can be used in container apps (ms2Service)
> Publish CSS themes

- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/components/Header.tsx
- packages/app/src/components/MainPage.tsx
- packages/app/src/components/index.ts
- packages/app/src/index.ts
- packages/app/src/main.tsx
- packages/app/vite.config.ts
- packages/sdk/package.json
- packages/sdk/src/components/AnalyzePackageButton.tsx
- packages/sdk/vite.config.ts
- packages/server/package.json
Creates/Exposes HeaderProps so that MS2 Service can customize header while using useNavigation for breadcrumbs etc.
> Create HeaderProps hack

- examples/data-app/src/TemplateFrame.tsx
- examples/data-app/src/components/AddChartDialog.tsx
- examples/data-app/src/components/Dashboard.tsx
- examples/data-app/src/components/SideMenu.tsx
- examples/data-app/vite.config.ts
- packages/sdk/src/components/Model/Model.tsx
- packages/sdk/src/components/Package/index.ts
- packages/sdk/src/components/Project/index.ts
Create a dynamic chart via an "add dialog" button which opens a selector for package/model, then opens the explorere
> Add dialog for dynamic charts

- packages/sdk/src/components/Project/About.tsx
> Fix Readme crash when missing

- packages/sdk/src/components/Project/ConnectionExplorer.tsx
Makes it 3-paned to display table schemas and optionally 2-paned if schema is already specified.
> Update Connection Explorer component

- packages/sdk/src/components/Project/ConnectionExplorer.tsx
- packages/server/src/errors.ts
- packages/server/src/service/db_utils.ts
Query compilation errors are now 400's
> fix alignment on schema explorer

- examples/data-app/package-lock.json
- examples/data-app/package.json
- examples/data-app/vite.config.ts
> fix optimization which caused explorer to break in dev mode

- api-doc.yaml
- bun.lock
- packages/server/package.json
- packages/server/publisher.config.json
- packages/server/src/controller/package.controller.ts
- packages/server/src/server.ts
- packages/server/src/service/project.ts
- packages/server/src/service/project_store.ts
This PR lets the publisher fetch and load projects and packages from remote origins during boot. It also addresses security concerns about relative paths by disallowing them.
> Add GCS+S3+GH compatibility

- packages/app/src/components/Header.tsx
- packages/app/src/components/WorkbookPage.tsx
- packages/sdk/src/components/AnalyzePackageButton.tsx
- packages/sdk/src/components/Workbook/BrowserWorkbookStorage.ts
- packages/sdk/src/components/Workbook/Workbook.tsx
- packages/sdk/src/components/Workbook/WorkbookList.tsx
- packages/sdk/src/components/Workbook/WorkbookManager.ts
- packages/sdk/src/components/Workbook/WorkbookStorage.ts
* Workbook UI reports an error when no Workspaces are available (rather than using a null workspace)
* Removes Project/Package context from WorkspaceStorage interface.
* Fixes usePackage usage.
> Workbook Fixes

- packages/sdk/src/components/Workbook/MutableCell.tsx
- packages/sdk/src/components/Workbook/Workbook.tsx
Workbook's lost state sometimes during editing. This resolves these issues
> fix workbook state management

- packages/app/package.json
- packages/sdk/package.json
- packages/server/package.json
> Update SDK/App version to v0.0.90

- api-doc.yaml
- packages/sdk/src/components/Project/ConnectionExplorer.tsx
- packages/server/src/service/db_utils.ts
> add BQ schema descriptions to API & ConnectionExplorer

- bun.lock
- packages/sdk/package.json
> react-quer -> peer dep

- examples/data-app/src/components/AddChartDialog.tsx
- packages/app/src/components/HomePage.tsx
- packages/app/src/components/PackagePage.tsx
- packages/app/src/components/ProjectPage.tsx
- packages/sdk/src/components/Home/Home.tsx
- packages/sdk/src/components/Package/FileTreeView.tsx
- packages/sdk/src/components/Package/Models.tsx
- packages/sdk/src/components/Package/Notebooks.tsx
- packages/sdk/src/components/Package/Package.tsx
- packages/sdk/src/components/Project/Packages.tsx
- packages/sdk/src/components/Project/Project.tsx
Replaced generic navigate props with more descriptive prop names that better reflect the specific user interactions
> Remove navigate parameters and replace with onClick or onSelect

- packages/app/package.json
- packages/sdk/package.json
- packages/server/package.json
Automatically updated package.json versions.
> Update SDK/App/Server version to v0.0.110

- packages/app/src/theme.tsx
1955:- Publisher: Explorer + does not work when "magnified"
> fix the explorer magnified issue

- packages/server/package.json
- packages/server/src/service/connection.ts
- packages/server/src/service/db_utils.ts
- packages/server/src/service/model.ts
Added some checks for Trino connection and added testConfig for Trino and MySQL
> trino and mysql testConfig implementation
