malloydata/publisher

.github/workflows/build.yml
packages/server/package.json
packages/server/src/service/package.spec.ts

Fixes failing build https://github.com/malloydata/publisher/actions/runs/14766493098/job/41459212158 from https://github.com/malloydata/publisher/pull/48

fix: add missing @modelcontextprotocol/sdk dependency

---

packages/app/package.json
packages/app/vite.config.ts

`packages/app` now explicitly depends on `/sdk/src` in dev mode, so Hot reloading works (and the SDK code is not obfuscated)

Update app -> SDK dep so HMR works

---

README.md
packages/app/README.md

Moves dev instructions for running publisher server into the server README (which was a template).
Adds instructions for using a local copy of Malloy Render in local server.

Server README. Instructions for using local render code

---

packages/server/src/__tests__/mcp_execute_query_tool.integration.spec.ts
packages/server/src/__tests__/mcp_test_setup.ts
packages/server/src/api.ts
packages/server/src/controller/query.controller.ts
packages/server/src/dto/connection.dto.spec.ts
packages/server/src/dto/package.dto.spec.ts
packages/server/src/mcp/error_messages.ts
packages/server/src/mcp/tools/execute_query_tool.ts
packages/server/src/server.ts
packages/server/src/service/project.ts

This PR reverts a previous change to `QueryController.getQuery` that caused it to return an empty object instead of the actual query results. (see comment here: https://github.com/malloydata/publisher/pull/48#discussion_r2072640681)
- Reverted the logic in `packages/server/src/controller/query.controller.ts` to capture and return the data from `model.getQueryResults`.
- Ran `bun run format` and `bunx eslint --fix` on the `packages/server` directory to address numerous formatting inconsistencies and fix two `no-unused-expressions` errors in test files (`*.dto.spec.ts`).
- This restores the functionality of the `/api/v0/projects/:projectName/packages/:packageName/queryResults/*` endpoint.
----
This PR also fixes the `malloy/executeQuery` MCP tool, which failed to run nested views (e.g., …

Fix: Revert getQuery change and apply lint fixes

---

api-doc.yaml
packages/sdk/src/client/api.ts
packages/sdk/src/components/Package/Databases.tsx
packages/sdk/src/components/Package/Package.tsx
packages/server/src/api.ts
packages/server/src/service/package.spec.ts
packages/server/src/service/package.ts

* Embedded DBs are now clickable -> Table schema.
* Size -> Rows (seems more relevant?)
* Width fixed so only 2 cards/row
* Adds support for `.csv` as package embedded DBs
https://github.com/user-attachments/assets/f2d31361-1757-4e66-8d9e-4334e74ab6db

Adds database schema to package UI

---

packages/sdk/src/components/Model/Model.tsx
packages/sdk/src/components/styles.ts

To restrict graph heights, need to set explicit widths for each panel in the flex-container, otherwise it becomes unstable when rendering the scroll bar

Fix chart height issue in ModelExplorer

---

packages/sdk/package.json
packages/sdk/src/components/Model/Model.tsx

Explicitly export the malloy-explorer CSS (from styleX) so it can be imported by AdminApp (or other SDK consumers).
I think there's a way to configure JS bundlers to automatically find the CSS and use it, but I'm not sure how.

Export malloy-explorer.css

---

packages/app/src/components/ScatchNotebookPageList.tsx
packages/app/src/main.tsx
packages/sdk/src/components/Model/SourcesExplorer.tsx
packages/sdk/src/components/MutableNotebook/BrowserNotebookStorage.ts
packages/sdk/src/components/MutableNotebook/MutableCell.tsx
packages/sdk/src/components/MutableNotebook/MutableNotebook.tsx
packages/sdk/src/components/MutableNotebook/MutableNotebookList.tsx
packages/sdk/src/components/MutableNotebook/NotebookStorage.ts
packages/sdk/src/components/MutableNotebook/NotebookStorageProvider.tsx
packages/sdk/src/components/MutableNotebook/index.ts
packages/sdk/src/components/NotebookManager.ts
packages/sdk/src/components/Package/Package.tsx

Alternate UI would be to just show the Notebook list in the package page directly. Saves space and clicks, but might be more limiting if the UI expands (folders, sharing, etc..)
Also worth noting that "MutableNotebookList" is entirely Cursor-written, with only 1 minor edit
https://github.com/user-attachments/assets/fbe69807-4719-4a2d-83a1-e37059fcaf2f

Adds NotebookStorage API, Notebook ListUI

---

bun.lock

This PR allows installing dependencies with a frozen lockfile
```sh
❯ bun i --frozen-lockfile
bun install v1.2.10 (db2e7d7f)
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
❯ bun i
bun install v1.2.10 (db2e7d7f)
❯ bun i --frozen-lockfile
bun install v1.2.10 (db2e7d7f)
Checked 1960 installs across 1801 packages (no changes) [457.00ms]
```

Fix lockfile

---

packages/sdk/vite.config.ts

This PR fixes an issue where the sdk needed over 4GB ram to build and it would crash when building with constrained resources

Fix memory management during sdk build

---

packages/app/src/theme.tsx
packages/app/src/theme/customizations/surfaces.ts
packages/sdk/src/components/Notebook/NotebookCell.tsx

* Fixes https://github.com/ms2data/service/issues/726#issue-3107785790 -
Adds a miniumum height to the notebookCell
* Applies MUI styling to compactify Cards & icons

Fix notebook rerender, add in MUI styling overrides

---

packages/app/src/components/HomePage.tsx
packages/app/src/components/MainPage.tsx
packages/app/src/components/MutableNotebookList.tsx
packages/app/src/components/PackagePage.tsx
packages/app/src/components/ProjectPage.tsx
packages/sdk/src/components/Home/Home.tsx
packages/sdk/src/components/MutableNotebook/MutableNotebook.tsx
packages/sdk/src/components/Package/Connections.tsx
packages/sdk/src/components/Package/FileTreeView.tsx
packages/sdk/src/components/Package/Models.tsx
packages/sdk/src/components/Package/Notebooks.tsx
packages/sdk/src/components/Package/Package.tsx
packages/sdk/src/components/Project/Packages.tsx
packages/sdk/src/components/Project/Project.tsx
packages/sdk/src/components/RenderedResult/ResultContainer.tsx
packages/sdk/src/components/click_helper.ts
packages/sdk/src/components/index.ts

Navigation should be replaced by a provider, so it does not need to be part of the prop render tree.

Ctrl-click and other normal click options work in the UI

---

packages/sdk/src/components/ApiErrorDisplay.tsx
packages/sdk/src/components/Home/Home.tsx
packages/sdk/src/components/Model/Model.tsx
packages/sdk/src/components/Model/NamedQueries.tsx
packages/sdk/src/components/Model/SourcesExplorer.tsx
packages/sdk/src/components/MutableNotebook/ModelPicker.tsx
packages/sdk/src/components/Notebook/Notebook.tsx
packages/sdk/src/components/Package/Config.tsx
packages/sdk/src/components/Package/Connections.tsx
packages/sdk/src/components/Package/Databases.tsx
packages/sdk/src/components/Package/Models.tsx
packages/sdk/src/components/Package/Notebooks.tsx
packages/sdk/src/components/Package/Schedules.tsx
packages/sdk/src/components/Project/About.tsx
packages/sdk/src/components/Project/ConnectionExplorer.tsx
packages/sdk/src/components/Project/Packages.tsx
packages/sdk/src/components/QueryResult/QueryResult.tsx
packages/sdk/src/hooks/useQueryWithApiError.ts

Cursor Refactoring:
Replaces direct use of useQuery/useMutation with consolidated utility.
Utility does error handing (extracting error payload from the thrown AxiosError
Utilty uses a Centralized QueryClient (so it can actually cache things reliably across components.

Refactor ReactQuery usage for error handling

---

packages/app/vite.config.ts
packages/sdk/vite.config.ts
packages/sdk/vite.config.ts.timestamp-1732998513502-40117fb4923d1.mjs

This PR fixes a bug where the malloy SDK would always bundle the `development` version of React 19, causing apps built with the `production` version of React 19 to crash by referencing undefined methods.

Fix SDK build

---

docs/ai-agents.md

Remove TODO: check if claude pro subscription is required.
I created a new claude Free account and confirmed on my desktop that the free account can still access the local malloy MCP server, so I am removing the sentence which says you might need a subscription.

docs(ai-agents): update AI agents documentation

---

examples/data-app/src/components/SingleEmbedDashboard.tsx

The SingleEmbedDashboard component wasn't rendering embedded query results properly, while the same query strings worked fine in DynamicDashboard.
- Container styling was different from DynamicDashboard
- String processing for newlines wasn't consistent with UI behavior
- Users had to manually escape newlines when pasting from UI
- Updated container styling to match DynamicDashboard (width: 90%, height: 396px, overflow: visible)
- Added automatic string processing: `rawEmbeddedQuery.replace(/\\n/g, '\n').replace(/\n/g, '\\n')`
- Users can now paste query strings directly from UI without manual escaping
- Cleaned up debug code and console logs
- Verified that query strings copied from DynamicDashboard UI work directly in SingleEmbedDashboard
- Confirmed that both escaped and unescaped …

Fix SingleEmbedDashboard embedded query string handling

---

README.md
docs/ai-agents.md

- **README.md**: Updated git clone command to use HTTPS instead of SSH
- **docs/ai-agents.md**: 
- Fixed malformed markdown links in git clone commands
- Updated repository references from `malloydata/malloy-samples` to `ms2data/malloy-samples`
- Fixed malloy_bridge.py download link to point to correct repository path

Fix documentation links and repository references

---

examples/data-app/src/components/AddChartDialog.tsx
packages/sdk/src/components/Model/Model.tsx
packages/sdk/src/components/Model/ModelExplorer.tsx
packages/sdk/src/components/Model/SourcesExplorer.tsx
packages/sdk/src/components/Model/index.ts
packages/sdk/src/components/Model/useModelData.ts
packages/sdk/src/components/styles.ts

Pulls out Explorer display from Model Page.
Fixes Flex issues causing squished line graphs
Fixes "clear" -> new_query  causing old result display

Refactor ModelExplorer

---

packages/server/src/server.ts
packages/server/src/service/package.ts
packages/server/src/service/project.ts

Adds a 30s timeout to individual package loading.
As soon as server starts, it begins initializing packages. Hopefully this will resolve some startup waiting time issues in CI?

Add timeouts to package loading. init server

---

examples/data-app/src/main.tsx
packages/app/src/App.tsx
packages/app/src/main.tsx
packages/sdk/src/components/Home/Home.tsx
packages/sdk/src/components/Model/ModelCell.tsx
packages/sdk/src/components/Model/SourcesExplorer.tsx
packages/sdk/src/components/Model/useModelData.ts
packages/sdk/src/components/Notebook/Notebook.tsx
packages/sdk/src/components/Package/Config.tsx
packages/sdk/src/components/Package/Connections.tsx
packages/sdk/src/components/Package/Databases.tsx
packages/sdk/src/components/Package/Models.tsx
packages/sdk/src/components/Package/Notebooks.tsx
packages/sdk/src/components/Package/Schedules.tsx
packages/sdk/src/components/Project/About.tsx
packages/sdk/src/components/Project/ConnectionExplorer.tsx
packages/sdk/src/components/Project/Packages.tsx
packages/sdk/src/components/QueryResult/QueryResult.tsx
packages/sdk/src/components/ServerProvider.tsx
packages/sdk/src/components/Workbook/ModelPicker.tsx
packages/sdk/src/components/Workbook/Workbook.tsx
packages/sdk/src/hooks/index.ts
packages/sdk/src/hooks/useQueryWithApiError.ts
packages/sdk/src/hooks/useRawQueryData.ts
packages/sdk/src/index.ts
packages/sdk/src/utils/formatting.ts

This pr replaces direct API client instantiation with a new `useApiClients` hook from the ServerProvider across all components, it centralizes API client management and removes `config` imports.

Move Axios Client into ServerProvider

---

packages/app/vite.config.ts

Disable manual chunking to resolve circular dependency errors that were preventing the React app from loading. The previous chunking configuration was causing initialization order issues where variables were accessed before initialization in emotion/MUI dependencies.
This change bundles all dependencies together to ensure proper initialization order and resolves the blank page issue.
Fixes: "Cannot access 'z' before initialization" and similar errors

Fix vite bundling initialization order issues

---

packages/server/src/service/project.ts
packages/server/src/service/project_store.ts

+ Package Name Not Matching Bug Fix
+ Updated listPackages logic to match with listProjects (similar to earlier Sidecar). This approach will only focus on listing packages that were loaded via Publisher during the current runtime
+ Added marking packages to SERVING during the inital project load from publisher.config.json (Earlier packageStatus was used for tracking package statuses for the packages added after the initial loading from the config file)

Package Name Not Matching Bug Fix + listPackages logic to match with listProjects (similar to earlier Sidecar)
